unless defined?(MAX_THREADS_COUNT)
  MAX_THREADS_COUNT = ENV.fetch('RAILS_MAX_THREADS', '20').to_i
  MIN_THREADS_COUNT = ENV.fetch('RAILS_MIN_THREADS', '5').to_i
  WORKERS_COUNT = ENV.fetch('RAILS_WORKERS', '2').to_i
  MAX_POOL_SIZE = WORKERS_COUNT * MAX_THREADS_COUNT + MIN_THREADS_COUNT
  MIN_POOL_SIZE = WORKERS_COUNT * MIN_THREADS_COUNT + 1
end
